#-------------------------------
# General Site Settings

title: 北京远信国际
logo:
author: 黄金
description: this is meta description
email: hj4246@163.com
phone: 131 4102 8813
address: 北京远信国际公司（中国）

menu:
  # - {name: 相关, link: '/about'}
  - { name: 案例介绍, link: '/news' }
# - {name: 简介, link: '/portfolio'}

project-cases-items:
  - image : "assets/images/project-cases/item-1.png"
    url: "#"

  - image : "assets/images/project-cases/item-2.png"
    url: "#"

  - image : "assets/images/project-cases/item-3.png"
    url: "#"

  - image : "assets/images/project-cases/item-4.png"
    url: "#"

  - image : "assets/images/project-cases/item-5.png"
    url: "#"


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"

  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
